### ISSUE TITLE
SagCouchException when Doc-Body contains "error" as key

### ISSUE THREAD

**Issue by WiTuLo** [sbisbee/sag#93]
If a document has a key called "error" -> Sag throws an exception.

Example Body

   "_id": "testentry",
   "_rev": "5-d629d1e715bc6f1a3aa989e09fa0f197",
   "images": "{'bild1.jpg', 'bild2.jpg', 'bild3.jpg', 'bild4.jpg'}",
   "error": "no previously error"

<b>Notice:</b>  Undefined property: stdClass::$reason in <b>/var/www/test/lib/sag/src/httpAdapters/SagHTTPAdapter.php</b> on line <b>72</b><br />
stdClass Object
(
    [error] => CouchDB Error: <b>no previously error</b> ()
)
<hr>
Quick Hack exstand the decodeResp and move it over "$json->error":

      if(isset($json)) {
        if($this->decodeResp) {
          <b>$response->body = $json;</b>
          return $response;
        }
        if(!empty($json->error)) {
          throw new SagCouchException("{$json->error} ({$json->reason})", $response->headers->_HTTP->status);
        }

      }

**Comment by sbisbee** [comment]
Why not just store null or forget the field completely if there aren't errors?

Also, the code that you're referring to is checking for the common CouchDB error field that the server sends back with a message. I suppose it could just do it for error HTTP status code, but that'd break backward compatibility.

Lastly, I highly recommend that you use the cURL adapter instead of the native HTTP adapter. Much better performance. The only reason to not use the cURL adapter is if you're on a server you don't control and cannot install the cURL bindings for some reason.
